# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: UMA GOVIND
email: info@umagovind.com
tagline: more about Uma
description: >- # this means to ignore newlines until "baseurl:"
   Uma Govind is a professional Bharata Natyam dancer. She is an empanelled artist with ICCR and SPICMACAY.
   She is also an "A" grade artist of National Doordarshan (Official Broadcaster of India)
baseurl: "" # the subpath of your site, e.g. /blog
mini_description: >-
  Doordarshan A grade, ICCR, SPICMACAY
url: "https://wwww.umagovind.com" # the base hostname & protocol for your site, e.g. http://example.com
timezone: "Asia/Kolkata"
locale: en_IN
show_excerpts: true

facebook_username: "umaugovind"
instagram_username: "umagovind"

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - about/index.markdown
  - services/index.markdown
  - gallery/index.markdown
  - reviews/index.markdown
  - contact/index.markdown
  - performances/index.markdown


defaults:
  -
    scope:
      path: "assets/images/gallery" # an empty string here means all files in the project
    values:
      image: true


algolia:
   application_id: '6X1KSL8VIY'
   index_name: 'prod_umagovind.com'
   search_only_api_key: '5734806a2062c667696361c2df5226c7'

  #webmaster_verifications:
  #google: 1234
  #bing: 1234
  #alexa: 1234
  #yandex: 1234
  #baidu: 1234

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
